### PR TITLE
Updating runtimes folders

### PR DESCRIPTION
**Pull request by bvennam**

### CODE REVIEW

**Comment by bvennam** [comment]
@csantanapr please review & feel free to merge if it LGTY

**Review by csantanapr — DISMISSED** [review]
@beemarie 
Tests are not running for PRs
Need to remove this line:
https://github.com/ibm-functions/template-cloudant-trigger/blob/master/tools/travis/build.sh#L14

**Comment by beemarie** [comment]
@jasonpet feel free to merge if it LGTY

**Comment by bvennam** [comment]
@dubeejw feel free to merge if it LGTY

**Review by dubee — APPROVED** [review]

**Pull request merged**
